# Generated by Django 2.2.6 on 2019-10-03 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('type_route', models.CharField(choices=[('BS', 'Автобус'), ('SE', 'Маршрутное такси'), ('TM', 'Трамвай')], default='BS', max_length=2)),
                ('map_city', models.ImageField(default='maps/none.png', unique=True, upload_to='maps')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('type_vehicle', models.CharField(choices=[('BS', 'Автобус'), ('SE', 'Маршрутное такси'), ('TM', 'Трамвай')], default='BS', max_length=2)),
                ('route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('route', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='backend.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatars/none.png', unique=True, upload_to='avatars')),
                ('vahicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Vehicle')),
            ],
        ),
    ]
