# Generated by Django 2.2.6 on 2019-10-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
